### ISSUE TITLE
Ordering of items is incorrect.

### ISSUE THREAD

**Issue by ab623** [thingybase/community#12]
The ordering on many the items in my containers are wrong. Seems like they are being ordered but in 2 parts. If it helps The botth half was created using the old input method, and the top half was created used the new quick add method. 

![image](https://user-images.githubusercontent.com/3438974/127835789-a5d58493-bd90-4265-aadc-9f2ede7088a6.png)

**Comment by bradgessler** [comment]
I'm seeing that too, and as you point out, it behaves differently depending on where you are inserting items. Fixing should be straight forward, but before I do that what ordering do you want to see by default? I think the reasonable options at this point are:

1. `[ Container | Not a container ] → Name`
2. `Name`

Eventually I will make it so that you can change how you sort the views, which I'll track in a separate ticket. For now we'll call this can be quickly resolved.

**Comment by ab623** [comment]
Sounds good. For me I would sort by Container A-Z first, then Items A-Z.

**Comment by bradgessler** [comment]
Issue was fixed and deployed to production. Order should be `Container A-Z first, then Items A-Z`; if you see otherwise just reply after this issue is closed.

**Comment by ab623** [comment]
Hey Brad, just checked. Still seeing this issue in multiple places.

**Comment by bradgessler** [comment]
Could you paste the URLs where you're seeing that? I don't need to look at the specific account so you can remove or alter the IDs, but seeing those will help me narrow down the issue.

I confirmed that I could see the issue at:

* https://www.thingybase.com/accounts/:uid/items
* https://www.thingybase.com/accounts/:uid/items/batches/new
* https://www.thingybase.com/items/:uid
* https://www.thingybase.com/items/:uid/batches/new

Which (I think) I was able to resolve

**Comment by bradgessler** [comment]
Hold off on those URLs! I pulled up a test account with more complex data and see the issue still persists.

I'll take a closer look at it and get back when I figure out what's going on with that.

**Comment by bradgessler** [comment]
I made the wrong assumption that the database value for items.container was t/f, but it also includes null. When an item is created that field is null by default. If the item is edited and changed into a group, and then back, it moves from null to false.

**Comment by bradgessler** [comment]
Confirmed that I was sorting on `null, true, false` when I assumed `true, false`. I fixed the issue and added a constraint to the database that will reject `null` values for `items.container`. I also updated existing `null` values to `false`, which will appear as an `Item` on the list.

I'll close the issue for now. If it's still around I'll open it again.
